server:
  port: 8761

spring:
  application:
    name: discovery-server

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
