server:
  port: 8084

spring:
  application:
    name: transaction-service

  cloud:
    openfeign:
      httpclient:
        enabled: false
      okhttp:
        enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:postgresql://localhost:5432/transaction_db
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: transactions

  flyway:
    enabled: true
    default-schema: transactions
    schemas: transactions
    locations: classpath:db/migration
    baseline-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      accountService:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

  retry:
    instances:
      accountService:
        max-attempts: 3
        wait-duration: 1s
        
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - circuitbreakers
          - circuitbreakerevents
          - retries
          - retryevents

  endpoint:
    health:
      show-details: always

  health:
    circuitbreakers:
      enabled: true

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  level:
    com.finflow.transaction_service: DEBUG
    feign: DEBUG
